In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.datasets import load_boston


ModuleNotFoundError: No module named 'pandas'

In [ ]:
bos_df=load_boston()
bos_df.keys()


C:\Users\trish\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])

In [ ]:
print(bos_df.data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [ ]:
print(bos_df.feature_names)

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


### Preparing the Dataset

In [ ]:
dataset=pd.DataFrame(bos_df.data, columns=bos_df.feature_names)
dataset.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [ ]:
dataset['Price']=bos_df.target
dataset.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  Price  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  Price    506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB


In [2]:
 ### EXPLORATORY DATA ANALYSIS

In [3]:
dataset.corr()

NameError: name 'dataset' is not defined

In [4]:
import seaborn as sns
sns.pairplot(dataset)

ModuleNotFoundError: No module named 'seaborn'

In [5]:
plt.scatter(dataset['CRIM'], dataset['Price'])
plt.xlabel("Crime rate")
plt.ylabel("Price")

NameError: name 'plt' is not defined

In [6]:
plt.scatter(dataset['RM'], dataset['Price'])
plt.xlabel("Average No. of Rooms")
plt.ylabel("Price")

NameError: name 'plt' is not defined

In [7]:
import seaborn as sns 
sns.regplot(x="RM", y="Price", data=dataset)
## shows positive correlation

ModuleNotFoundError: No module named 'seaborn'

In [8]:
sns.regplot(x="LSTAT", y="Price", data=dataset)
## shows negative correlation

NameError: name 'sns' is not defined

In [9]:
sns.regplot(x="CHAS", y="Price", data=dataset)
## shows NO correlation

NameError: name 'sns' is not defined

In [10]:
sns.regplot(x="PTRATIO", y="Price", data=dataset)
## shows INVERSE correlation

NameError: name 'sns' is not defined

In [11]:
## iNDEPENDENT AND dEPENDENT fEATURES

X=dataset.iloc[:,:-1 ]
Y=dataset.iloc[:,-1]
print(X.head(3))
print(Y.head(3))

NameError: name 'dataset' is not defined

In [12]:
## Train Test Split

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(X,Y,test_size=0.3, random_state=42)
x_train.head()

ModuleNotFoundError: No module named 'sklearn'

In [13]:
## Standardize the dataset

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
x_train

### interally we use Gradient Descent for which we need to come to global minima, for which all the independent feature unit should be in then same scale,so conn 

ModuleNotFoundError: No module named 'sklearn'

## Model Training

In [14]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()

ModuleNotFoundError: No module named 'sklearn'

In [15]:
reg.fit(x_train, y_train)


NameError: name 'reg' is not defined

In [16]:
 # printing the coeffcients
print(reg.coef_)
print(reg.intercept_)

NameError: name 'reg' is not defined

In [17]:
## training parameters of the model
reg.get_params()

NameError: name 'reg' is not defined

In [18]:
## prediction with test data
reg_pred=reg.predict(x_test)
reg_pred

NameError: name 'reg' is not defined

In [19]:
## plotting a scatter plot for the prediction
plt.scatter(y_test,reg_pred)

NameError: name 'plt' is not defined

In [20]:
## Residuals calculation
residuals=y_test-reg_pred
residuals

NameError: name 'y_test' is not defined

In [21]:
## Plotting the residuals
sns.displot(residuals, kind="kde")
## outliers on right side

NameError: name 'sns' is not defined

In [22]:
## Scatter plot wrt predictions and residuals
plt.scatter(reg_pred, residuals)

NameError: name 'plt' is not defined

In [23]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

print(mean_absolute_error(y_test,reg_pred))
print(mean_squared_error(y_test, reg_pred))
print(np.sqrt(mean_squared_error(y_test, reg_pred)))


ModuleNotFoundError: No module named 'sklearn'

### R Squared and Adjusted R squared


In [24]:
 from sklearn.metrics import r2_score
score=r2_score(y_test, reg_pred)
print(score)

ModuleNotFoundError: No module named 'sklearn'

In [25]:
# adjusted R-squared
1- (1-score)*(len(y_test)-1)/(len(y_test)-x_test.shape[1]-1)


NameError: name 'score' is not defined

## Data Prediction

In [26]:
bos_df.data[0].reshape(1,-1)

NameError: name 'bos_df' is not defined

In [27]:
#Standardization

scaled_data=scaler.transform(bos_df.data[0].reshape(1,-1))

NameError: name 'scaler' is not defined

In [28]:
reg.predict(scaled_data)

NameError: name 'reg' is not defined

## Pickling the Model file for Deployment

In [29]:
import pickle
pickle.dump(reg, open('regmodel.pkl','wb'))

NameError: name 'reg' is not defined

In [30]:
pickeled_model=pickle.load(open('regmodel.pkl','rb'))

ModuleNotFoundError: No module named 'sklearn'

In [31]:
## Prediction from Pickle file
pickeled_model.predict(scaled_data)

NameError: name 'pickeled_model' is not defined